### ISSUE TITLE
Incoming messages can be lost

### ISSUE THREAD

**Issue by BenUniqcode** [monstrenyatko/ArduinoMqtt#33] opened 2024-10-08 15:36 UTC
Hi. First of all, thanks for this library, it's mostly been very reliable and I love the configurability and control.

However I've found a problem that can result in incoming MQTT messages being permanently lost. 

I am using the latest release v1.5.1 in my project.

The issue arises when all of the following apply:

1. Client is reconnecting to a broker it has previously used, using `cleansession=false` and reusing an existing client id.
2. Client subscribes to more than one topic, or to a different topic than it did in the previous session.
3. One or more QoS 1 or 2 messages to one or more of the client's subscribed topics from its previous session, other than the first one it subscribes to in this session, are enqueued on the broker.

When a client is reconnecting a session with `cleansession=false`, the broker does not wait until the client resubscribes to a topic to send it messages for that topic; as soon as it connects, it immediately starts to send any queued messages for the client's subscriptions from its previous session. 

ArduinoMqtt handles this ok if the client only ever subscribes to one topic, because there is no opportunity between `connect()` and `subscribe()` for the incoming messages to be processed. So it calls `subscribe()` for the topic, sets up the message handler, and then processes the incoming messages, no problem. 

But if there is more than one subscribed topic, or the topic has changed, when `subscribe()` is called for the first time it will start to receive and process any queued messages for other topics as well. It acknowledges receipt of each message, and then calls `deliverMessage()` - which finds that there is not (yet) a handler defined for that topic, so it just says "Unexpected message" and throws it away!

There is a workaround, I think: instead of waiting until subscribe() to set up the message handlers, one can set them up beforehand, by explicitly calling `mqttMessageHandlers->set(topic, callback)` for each topic. However the necessity of doing this is not obvious, and it makes the requirement to specify the same callback to `subscribe()` as well seem a bit extraneous. 

To fix this properly would, I think, need a breaking change - but that might be justified to raise awareness and prevent others falling victim to this issue. It could be done by, for example, requiring `subscribe()` is called *before* connecting. It would set up the message handlers and keep a list of topics to be subscribed to, and the actual subscription requests would be sent on connect. Or, remove the `cbk` argument from `subscribe()`, and require that all message handler callbacks are registered before connect or before the first call to `subscribe()` - but that seems harder to enforce. 

Regardless, I think `processPacket()` **must not** send a PUBACK or PUBREC for an incoming PUBLISH packet if there is no message handler defined for the topic. This is a general matter of safety, not specific to this issue - acknowledging receipt of a message only to then throw it away without delivering it, is not the behaviour most people would expect. If you can't deliver it (because there's no handler, or because of any other temporary error) then don't ack it, so the broker will try again. If the user *wants* to discard certain messages, they can choose to do that, but the library should never do so by default! Making this fix should not break anything, and would at least ensure that the broker should attempt redelivery later, giving us time to complete all the subscriptions - however, it's possible that if we only make short-lived MQTT connections, the broker will simply keep trying to deliver the message at the wrong time, and so although it isn't lost as such, we will never receive it properly. 

I hope that all makes sense. If you can think of a better solution I'm all ears. I was going to simply make a PR but I thought this probably warrants some discussion first about the right approach. 

Cheers
Ben

**Comment by monstrenyatko** [comment] 2024-10-09 05:45
Hi @BenUniqcode , I added a small fix to check available handlers. I ignore messages with no handler set. `PUBACK` or `PUBREC` will not be sent in this case. I hope this resolves the problem.

BTW: I tried to reproduce the problem using `test.mosquitto.org` broker but it doesn't send anything until client resubscribes to the topic.

**Comment by BenUniqcode** [comment] 2024-10-13 14:43
Hi @monstrenyatko , thanks for your quick attention to this problem. 

I can't explain why it didn't work for you on test.mosquitto.org; I am using our own instance of Mosquitto as a broker, and it definitely sends queued messages for the previous subscriptions without waiting to see if the client resubscribes. Maybe there's some difference in config but I can't see it.

Anyway, the fix works. It does however cause another problem that I had not anticipated. If there are more queued messages for topics that are no longer subscribed, than the setting for `max_inflight_messages` in Mosquitto, then failing to ack these messages will completely block any messages for still-subscribed topics from getting through. We have `max_inflight_messages` set to `1` to guarantee that messages are delivered in the order they were sent, so a single undelivered message can now block all other messages. 

I can work around this by taking extra care to unsubscribe from old topics, or use cleansession, when I am changing the device's subscriptions. I just wanted to highlight it as a potential problem in case anyone else runs into it. I still think that the fix in de89ec6bf7ff21471ddea3e18afa3e106d3ea511 should stand. 

Cheers,
Ben

**Comment by BenUniqcode** [comment] 2024-10-13 17:06
Actually @monstrenyatko this can cause more problems than I first realised. 

I had hoped that if we have:

* subscribe to topicA
* message arrives for topicB - formerly would be discarded, now goes un-acked
* subscribe to topicB
* yield

then the broker would re-send the topicB message at this point. But it doesn't. 
Unfortunately, unacknowledged PUBLISH packets are only resent when the client first connects with a non-clean session (MQTT spec section 4.4).
So every time we connect, the same thing happens. So the topicB message will never be acknowledged, and (with max_inflight_messages=1) will block all other messages.

Another problem: If I was formerly subscribed to a topic, and then I unsubscribe from it, it's possible for a message to that topic to arrive in the middle of the unsubscribe. Then, even though the unsubscribe succeeds, because we did not acknowledge the PUBLISH, the broker will keep trying to send it every time we connect - and we no longer have a message handler for it because from the client's perspective we successfully unsubscribed. 

This problem is explicitly referenced in the MQTT spec section 4.5.0, which concludes: "The Client MUST acknowledge any Publish packet it receives according to the applicable QoS rules regardless of whether it elects to process the Application Message that it contains". 

In other words, I think we need to revert this change. 

The correct solution is, after all, to require that all message handlers are set up *before* connecting to the server. This is the way most other MQTT libraries work.

There are other advantages to this - it means there is no need to subscribe every time we connect, if connecting to an existing session and the topics have not changed, saving bandwidth. 

Also, I would like to be able to have message handlers with overlapping topics, such as "foo/bar" and "foo/#", but only the first matched one will be run. One possibility is to have a bool return type for the callback instead of void - if false, continue to look for other matches, if true stop processing. This would give the most flexibility as each handler could decide at runtime whether the processing of that message needs to fall through. 
deliverMessage() would do something like
```
- 					mMessageHandlers.get()[i].cbk(md);
- 					delivered = true;
+					delivered = mMessageHandlers.get()[i].cbk(md);
+					if (delivered)  break;
```

A less flexible but simpler way would be just to have a config option to choose whether all matching handlers are run (the default, to match what happens currently) or only the first. 
```
 					mMessageHandlers.get()[i].cbk(md);
 					delivered = true; 
+  					if (firstMatchOnly) break;
```
What do you think?

Ben

**Comment by monstrenyatko** [comment] 2024-10-16 06:10
@BenUniqcode , hmm, it looks like this causes even more problems. I'll revert the change de89ec6bf7ff21471ddea3e18afa3e106d3ea511 and take a look at the ability to set handlers with no need for subscribe call.

About "overlapping topics", the `deliverMessage` implementation delivers messages to all handlers that match the topic. You can set a single wildcard handler and just parse the topic value on the application side. But for this, I need to disconnect the callback setup from the subscription call.

**Comment by monstrenyatko** [comment] 2024-10-16 08:32
It looks like If I simply remove message handlers management this will do the trick. The `subscribe` will not need a callback parameter. Everybody can manage (add/remove) handlers using the `MessageHandlers` object.

**Comment by BenUniqcode** [comment] 2024-10-16 11:18
Yes that's what I'm currently doing, using `mqttMessageHandlers.set()` for each topic before connecting. Then `subscribe()`, instead of setting up the message handler, just needs to check that a message handler exists that will match for the given topic.

**Comment by monstrenyatko** [comment] 2024-10-16 18:58
> Yes that's what I'm currently doing, using `mqttMessageHandlers.set()` for each topic before connecting. Then `subscribe()`, instead of setting up the message handler, just needs to check that a message handler exists that will match for the given topic.

I do not think `subscribe()` needs to check anything. We can fully disconnect handlers management from the subscription. The MQTT client will not modify handlers.

**Comment by monstrenyatko** [comment] 2024-10-17 05:38
@BenUniqcode , in the latest change the library no longer manages the `MessageHandlers` content.

You will be able to set all handlers in advance and fully avoid calling to `subscribe` when the session is present on the broker. Additionally, you are not required to use exactly the same topic value for the `subscribe` call and in  `MessageHandler`.

**Comment by monstrenyatko** [comment] 2024-11-25 03:03
Assuming the issue is resolved with the latest change, I'm closing this ticket.

**Closed by monstrenyatko** 2024-11-25 03:03 UTC

**Comment by gmatocha** [comment] 2025-04-28 21:30
Great catch BenUnicode, and great thread but it creates a big breaking change. Might I suggest a kinder fix to the fix?
1. Set a null default value for the callback parameter in subscribe.
2. If callback is set, process it as in 1.5.1.
3. If callback is null, check for an existing handler. If not present, return error.
4. Document that if BenUnicode's scenario is of concern to the user, they should pre-populate MessageHandler and not pass callbacks to subscribe.
